### ISSUE TITLE
Add a method to generate a QR code that any website could implement for signing in with DID

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.DID.JS.SDK#2]
This QR code can be scanned from elastOS or elephant or whatever else

**Comment by BenjaminPiette** [comment]
This should be provided by the upcoming connectivity SDK. The DID SDK should keep low level features mostly. Instead, applications will have to add the elastos connectivity sdk, together with "connectors" (local connector, essentials connectors, etc), in order to display such popup. For example, the connectivity SDK itself will be responsible for displaying a first popup that will let users choose their "connectors" (sign in with essentials, sign in with something else). Then, if the essentials connector is chosen, the essentials connector itself will display what it needs to let users sign in wit htheir mobile app, including a QR code to be scanned.

This task could be closed but let's discuss this on discord to make sure we are aligned on the way to do this.
